# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c58d36898fbc3f878f34af2d9d67e4ca44fa5bb189aa63170fb6e109af1770d9fc78a7d62af93454350a7770c3040150ccac6aee91fc0aaeaedd8e36ec7252cb

test:
  secret_key_base: 33b3608a976add9977a2e7f0096b8a9e1798cf447ca2d1130875d86e39ecfcdc567ecf1d4af029987bf1ea3bd285ad0ac374722949223aa103282091b17679d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
